// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package api

type Match struct {
	ID        string         `json:"id"`
	Sport     *Sport         `json:"sport"`
	Timestamp int            `json:"timestamp"`
	Teams     []*Team        `json:"teams"`
	Results   []*MatchResult `json:"results"`
}

type MatchResult struct {
	Score int   `json:"score"`
	Team  *Team `json:"team"`
}

type Sport struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Team struct {
	Players []*User `json:"players"`
}

type User struct {
	ID        string  `json:"id"`
	Nickname  string  `json:"nickname"`
	AuthToken *string `json:"authToken"`
}
