version: "3.7"
services:
  database:
    image: "postgres:latest"
    env_file:
      - containers/config/database.env
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/postgresql/data
    ports:
      - "5432:5432"
  webserver:
    build:
      context: ./
      dockerfile: ./containers/config/WebServerDockerfile
    env_file:
      - containers/config/database.env
      - containers/config/api.env
    volumes:
      - ./containers/static:/app
    ports:
      - "8080:8080"
    links:
      - database
    stdin_open: true
    tty: true
volumes:
  dbdata:
